//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjUcbWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsBase() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrjUcbWeb.Resources.RsBase", typeof(RsBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Administrador.
        /// </summary>
        public static string ADMINISTRADOR {
            get {
                return ResourceManager.GetString("ADMINISTRADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        public static string ALTERAR {
            get {
                return ResourceManager.GetString("ALTERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar Turma.
        /// </summary>
        public static string ALTERAR_TURMA {
            get {
                return ResourceManager.GetString("ALTERAR_TURMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar Usuário.
        /// </summary>
        public static string ALTERAR_USUARIO {
            get {
                return ResourceManager.GetString("ALTERAR USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção!.
        /// </summary>
        public static string ATENCAO_ {
            get {
                return ResourceManager.GetString("ATENCAO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar.
        /// </summary>
        public static string CADASTRAR {
            get {
                return ResourceManager.GetString("CADASTRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Turma.
        /// </summary>
        public static string CADASTRAR_TURMA {
            get {
                return ResourceManager.GetString("CADASTRAR_TURMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Usuário.
        /// </summary>
        public static string CADASTRAR_USUARIO {
            get {
                return ResourceManager.GetString("CADASTRAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de Turma.
        /// </summary>
        public static string COD_TURMA {
            get {
                return ResourceManager.GetString("COD_TURMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cod. Turma ou Professor.
        /// </summary>
        public static string CODTURMA_OU_PROF {
            get {
                return ResourceManager.GetString("CODTURMA_OU_PROF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criar.
        /// </summary>
        public static string CRIAR {
            get {
                return ResourceManager.GetString("CRIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disciplina.
        /// </summary>
        public static string DISCIPLINA {
            get {
                return ResourceManager.GetString("DISCIPLINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        public static string EXCLUIR {
            get {
                return ResourceManager.GetString("EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exportar.
        /// </summary>
        public static string EXPORTAR {
            get {
                return ResourceManager.GetString("EXPORTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gravar.
        /// </summary>
        public static string GRAVAR {
            get {
                return ResourceManager.GetString("GRAVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hora Fim.
        /// </summary>
        public static string HORA_FIM {
            get {
                return ResourceManager.GetString("HORA_FIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hora Inicio.
        /// </summary>
        public static string HORA_INICIO {
            get {
                return ResourceManager.GetString("HORA_INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horário.
        /// </summary>
        public static string HORARIO {
            get {
                return ResourceManager.GetString("HORARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou Id.
        /// </summary>
        public static string ID_OU_USUARIO {
            get {
                return ResourceManager.GetString("ID_OU_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exibindo {0} até {1} de um total de {2} registro(s)..
        /// </summary>
        public static string INFODATATABLE {
            get {
                return ResourceManager.GetString("INFODATATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informação!.
        /// </summary>
        public static string INFORMACAO {
            get {
                return ResourceManager.GetString("INFORMACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicio.
        /// </summary>
        public static string INICIO {
            get {
                return ResourceManager.GetString("INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Listagem de Turmas.
        /// </summary>
        public static string LISTAGEM_TURMA {
            get {
                return ResourceManager.GetString("LISTAGEM_TURMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Listagem de Usuários.
        /// </summary>
        public static string LISTAGEM_USUARIO {
            get {
                return ResourceManager.GetString("LISTAGEM_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro selecionado!.
        /// </summary>
        public static string NENHUM_REGISTRO {
            get {
                return ResourceManager.GetString("NENHUM_REGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string NOME {
            get {
                return ResourceManager.GetString("NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preenchimento obrigatório.
        /// </summary>
        public static string PREENCHIMENTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("PREENCHIMENTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PrjUcbWeb.
        /// </summary>
        public static string PRJUCBWEB {
            get {
                return ResourceManager.GetString("PRJUCBWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Professor.
        /// </summary>
        public static string PROFESSOR {
            get {
                return ResourceManager.GetString("PROFESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quant. Alunos.
        /// </summary>
        public static string QUANT_ALUNOS {
            get {
                return ResourceManager.GetString("QUANT_ALUNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de Alunos.
        /// </summary>
        public static string QUANTIDADE_ALUNOS {
            get {
                return ResourceManager.GetString("QUANTIDADE_ALUNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione.
        /// </summary>
        public static string SELECIONE {
            get {
                return ResourceManager.GetString("SELECIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string SENHA {
            get {
                return ResourceManager.GetString("SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Usuário.
        /// </summary>
        public static string TIPO_USUARIO {
            get {
                return ResourceManager.GetString("TIPO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string USUARIO {
            get {
                return ResourceManager.GetString("USUARIO", resourceCulture);
            }
        }
    }
}
